import Head from "next/head";
import { useQuery, gql } from "@apollo/client";
import { REVIEWS } from "@/graphql/queries";
import { setToken, unsetToken } from "@/lib/auth";
import { useState } from "react";
import Link from "next/link";
import { useUser, useFetchUser } from "@/lib/authContext";

export default function Home() {
  const { data, error, loading } = useQuery(REVIEWS);
  // if (qloading) return <p>loading....</p>;
  // if (qerror) return <p>error</p>;
  
  const { user, userLoading } = useFetchUser();
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      
      {!userLoading &&
        (user ? (
          <div>
            {loading ? (
              <p>loading</p>
            ) : (
              <div>
                {data.reviews.data.map((review) => (
                  <div key={review.id}>
                    <div>{review.attributes.rating}</div>
                    <div>{review.attributes.title}</div>
                    <p>{review.attributes.body}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        ) : (
          <div>
            <h1>Unlimited movies, TV shows, and more.</h1>
            <h3>Watch anywhere. Cancel anytime.</h3>
            <h3>Ready to watch? Enter your email to create or restart your membership</h3>
          </div>
        ))}
      
    </>
  );
}
