import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SiteHeader from "@/components/SiteHeader";
import Category from "./categories";
import useFetch from "@/hooks/useFetch";
import { useQuery, gql } from "@apollo/client";

const REVIEWS = gql`
  query {
    reviews {
      data {
        id
        attributes {
          
          title
          rating
          body
        }
      }
    }
  }
`;

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const some = useFetch("http://localhost:1337/api/reviews")

  // const { data, error, loading } = useFetch("http://localhost:1337/api/reviews");
  const { data, error, loading } = useQuery(REVIEWS);
  console.log(useQuery(REVIEWS))

  if (loading) return <p>loading....</p>;
  if (error) return <p>error</p>;

  // console.log(data);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data.reviews.data.map(review => (
          <div key={review.id}>
            <div>{review.attributes.rating}</div>
            <div>{review.attributes.title}</div>
            <p>{review.attributes.body}</p>
          </div>
          
        ))}
    </>
  );
}
